language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3

jobs:
  include:
    # Special Linux builds
    - name: "Python: 3.8, pure (no C extensions)"
      python: 3.8
      env: PURE_PYTHON=1

install:
    - pip install -U pip
    - pip install -U setuptools zc.buildout
    - buildout $BUILOUT_OPTIONS
script:
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then bin/coverage run bin/coverage-test -v; fi
    - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then bin/test -v; fi
    - if [[ $TRAVIS_PYTHON_VERSION != pypy3* ]]; then pip install --upgrade --requirement doc/requirements.txt; fi
    - if [[ $TRAVIS_PYTHON_VERSION != pypy3* ]]; then make -C doc html; fi
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi # install early enough to get into the cache
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then bin/coverage combine; fi
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
notifications:
    email: false
cache:
  directories:
    - $HOME/.cache/pip
    - eggs
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
