environment:
  matrix:
    - python: 27
    - python: 27-x64
    - python: 34
    - python: 34-x64
    - python: 35
    - python: 35-x64
    - python: 36
    - python: 36-x64
    - python: 37
    - python: 37-x64

install:
  - "SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%"
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\vcvars64.bat"
  - pip install -e .
  - pip install zope.testrunner zope.testing manuel
  - pip install zc.buildout zc.recipe.testrunner zc.recipe.egg

build_script:
  - buildout bootstrap
  - bin\buildout parts=test

test_script:
  - bin\test -vvv
